package envfile

import (
	"fmt"
	"os"
	"strings"
)

// WriteEnv writes or updates environment variables in .env file
func WriteEnv(pairs map[string]string) error {
	envPath := ".env"

	// Read existing .env if it exists
	existing := make(map[string]string)
	if data, err := os.ReadFile(envPath); err == nil {
		lines := strings.Split(string(data), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				existing[parts[0]] = parts[1]
			}
		}
	}

	// Update with new values
	for key, value := range pairs {
		existing[key] = value
	}

	// Write back to .env
	var lines []string
	lines = append(lines, "# Environment Configuration")
	lines = append(lines, "# Generated by mycart installer")
	lines = append(lines, "")

	for key, value := range existing {
		lines = append(lines, fmt.Sprintf("%s=%s", key, value))
	}

	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile(envPath, []byte(content), 0644)
}
