// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digital_data.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createDigitalData = `-- name: CreateDigitalData :one
INSERT INTO digital_data (id, product_id, content, cart_id)
VALUES (?, ?, ?, ?)
RETURNING id, product_id, content, cart_id
`

type CreateDigitalDataParams struct {
	ID        string         `json:"id"`
	ProductID string         `json:"product_id"`
	Content   string         `json:"content"`
	CartID    sql.NullString `json:"cart_id"`
}

func (q *Queries) CreateDigitalData(ctx context.Context, arg CreateDigitalDataParams) (DigitalDatum, error) {
	row := q.queryRow(ctx, q.createDigitalDataStmt, createDigitalData,
		arg.ID,
		arg.ProductID,
		arg.Content,
		arg.CartID,
	)
	var i DigitalDatum
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Content,
		&i.CartID,
	)
	return i, err
}

const deleteDigitalData = `-- name: DeleteDigitalData :exec
DELETE FROM digital_data WHERE id = ?
`

func (q *Queries) DeleteDigitalData(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteDigitalDataStmt, deleteDigitalData, id)
	return err
}

const deleteDigitalDataByProduct = `-- name: DeleteDigitalDataByProduct :exec
DELETE FROM digital_data WHERE product_id = ?
`

func (q *Queries) DeleteDigitalDataByProduct(ctx context.Context, productID string) error {
	_, err := q.exec(ctx, q.deleteDigitalDataByProductStmt, deleteDigitalDataByProduct, productID)
	return err
}

const getDigitalData = `-- name: GetDigitalData :one
SELECT id, product_id, content, cart_id
FROM digital_data WHERE id = ? LIMIT 1
`

func (q *Queries) GetDigitalData(ctx context.Context, id string) (DigitalDatum, error) {
	row := q.queryRow(ctx, q.getDigitalDataStmt, getDigitalData, id)
	var i DigitalDatum
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Content,
		&i.CartID,
	)
	return i, err
}

const getDigitalDataByProduct = `-- name: GetDigitalDataByProduct :one
SELECT id, product_id, content, cart_id
FROM digital_data WHERE product_id = ? LIMIT 1
`

func (q *Queries) GetDigitalDataByProduct(ctx context.Context, productID string) (DigitalDatum, error) {
	row := q.queryRow(ctx, q.getDigitalDataByProductStmt, getDigitalDataByProduct, productID)
	var i DigitalDatum
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Content,
		&i.CartID,
	)
	return i, err
}

const listAllDigitalData = `-- name: ListAllDigitalData :many
SELECT id, product_id, content, cart_id
FROM digital_data ORDER BY id
`

func (q *Queries) ListAllDigitalData(ctx context.Context) ([]DigitalDatum, error) {
	rows, err := q.query(ctx, q.listAllDigitalDataStmt, listAllDigitalData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalDatum{}
	for rows.Next() {
		var i DigitalDatum
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Content,
			&i.CartID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDigitalDataByCart = `-- name: ListDigitalDataByCart :many
SELECT id, product_id, content, cart_id
FROM digital_data WHERE cart_id = ?
`

func (q *Queries) ListDigitalDataByCart(ctx context.Context, cartID sql.NullString) ([]DigitalDatum, error) {
	rows, err := q.query(ctx, q.listDigitalDataByCartStmt, listDigitalDataByCart, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalDatum{}
	for rows.Next() {
		var i DigitalDatum
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Content,
			&i.CartID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDigitalData = `-- name: UpdateDigitalData :exec
UPDATE digital_data
SET content = ?
WHERE id = ?
`

type UpdateDigitalDataParams struct {
	Content string `json:"content"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateDigitalData(ctx context.Context, arg UpdateDigitalDataParams) error {
	_, err := q.exec(ctx, q.updateDigitalDataStmt, updateDigitalData, arg.Content, arg.ID)
	return err
}
