// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digital_files.sql

package sqlite

import (
	"context"
)

const createDigitalFile = `-- name: CreateDigitalFile :one
INSERT INTO digital_file (id, product_id, name, ext, orig_name)
VALUES (?, ?, ?, ?, ?)
RETURNING id, product_id, name, ext, orig_name
`

type CreateDigitalFileParams struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

func (q *Queries) CreateDigitalFile(ctx context.Context, arg CreateDigitalFileParams) (DigitalFile, error) {
	row := q.queryRow(ctx, q.createDigitalFileStmt, createDigitalFile,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Ext,
		arg.OrigName,
	)
	var i DigitalFile
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Ext,
		&i.OrigName,
	)
	return i, err
}

const deleteDigitalFile = `-- name: DeleteDigitalFile :exec
DELETE FROM digital_file WHERE id = ?
`

func (q *Queries) DeleteDigitalFile(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteDigitalFileStmt, deleteDigitalFile, id)
	return err
}

const deleteDigitalFiles = `-- name: DeleteDigitalFiles :exec
DELETE FROM digital_file WHERE product_id = ?
`

func (q *Queries) DeleteDigitalFiles(ctx context.Context, productID string) error {
	_, err := q.exec(ctx, q.deleteDigitalFilesStmt, deleteDigitalFiles, productID)
	return err
}

const getDigitalFile = `-- name: GetDigitalFile :one
SELECT id, product_id, name, ext, orig_name
FROM digital_file WHERE id = ? LIMIT 1
`

func (q *Queries) GetDigitalFile(ctx context.Context, id string) (DigitalFile, error) {
	row := q.queryRow(ctx, q.getDigitalFileStmt, getDigitalFile, id)
	var i DigitalFile
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Ext,
		&i.OrigName,
	)
	return i, err
}

const listDigitalFiles = `-- name: ListDigitalFiles :many
SELECT id, product_id, name, ext, orig_name
FROM digital_file WHERE product_id = ?
`

func (q *Queries) ListDigitalFiles(ctx context.Context, productID string) ([]DigitalFile, error) {
	rows, err := q.query(ctx, q.listDigitalFilesStmt, listDigitalFiles, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalFile{}
	for rows.Next() {
		var i DigitalFile
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Ext,
			&i.OrigName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
