// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
	"encoding/json"
)

type Cart struct {
	ID            string          `json:"id"`
	Email         sql.NullString  `json:"email"`
	AmountTotal   interface{}     `json:"amount_total"`
	Currency      string          `json:"currency"`
	PaymentID     sql.NullString  `json:"payment_id"`
	PaymentStatus sql.NullString  `json:"payment_status"`
	Cart          json.RawMessage `json:"cart"`
	Created       sql.NullTime    `json:"created"`
	Updated       sql.NullTime    `json:"updated"`
	PaymentSystem string          `json:"payment_system"`
}

type DigitalDatum struct {
	ID        string         `json:"id"`
	ProductID string         `json:"product_id"`
	Content   string         `json:"content"`
	CartID    sql.NullString `json:"cart_id"`
}

type DigitalFile struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

type Page struct {
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Slug     string          `json:"slug"`
	Content  sql.NullString  `json:"content"`
	Position string          `json:"position"`
	Active   bool            `json:"active"`
	Created  sql.NullTime    `json:"created"`
	Updated  sql.NullTime    `json:"updated"`
	Seo      json.RawMessage `json:"\"seo\""`
}

type Product struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Desc        string          `json:"desc"`
	Slug        string          `json:"slug"`
	Amount      interface{}     `json:"amount"`
	Metadata    json.RawMessage `json:"metadata"`
	Attribute   json.RawMessage `json:"attribute"`
	Digital     sql.NullString  `json:"digital"`
	Active      bool            `json:"active"`
	Deleted     bool            `json:"deleted"`
	Created     sql.NullTime    `json:"created"`
	Updated     sql.NullTime    `json:"updated"`
	Seo         json.RawMessage `json:"\"seo\""`
	Brief       string          `json:"\"brief\""`
	Quantity    sql.NullInt64   `json:"quantity"`
	Sku         sql.NullString  `json:"sku"`
	HasVariants sql.NullBool    `json:"has_variants"`
}

type ProductImage struct {
	ID        string        `json:"id"`
	ProductID string        `json:"product_id"`
	Name      string        `json:"name"`
	Ext       string        `json:"ext"`
	OrigName  string        `json:"orig_name"`
	Position  sql.NullInt64 `json:"position"`
}

type ProductOption struct {
	ID        string        `json:"id"`
	ProductID string        `json:"product_id"`
	Name      string        `json:"name"`
	Position  sql.NullInt64 `json:"position"`
	Created   sql.NullTime  `json:"created"`
}

type ProductOptionValue struct {
	ID       string        `json:"id"`
	OptionID string        `json:"option_id"`
	Value    string        `json:"value"`
	Position sql.NullInt64 `json:"position"`
}

type ProductVariant struct {
	ID             string          `json:"id"`
	ProductID      string          `json:"product_id"`
	Sku            sql.NullString  `json:"sku"`
	PriceSurcharge sql.NullFloat64 `json:"price_surcharge"`
	Quantity       sql.NullInt64   `json:"quantity"`
	OptionValues   string          `json:"option_values"`
	Active         sql.NullBool    `json:"active"`
	Deleted        sql.NullBool    `json:"deleted"`
	Created        sql.NullTime    `json:"created"`
	Updated        sql.NullTime    `json:"updated"`
}

type ProductVariantImage struct {
	ID        string        `json:"id"`
	VariantID string        `json:"variant_id"`
	Name      string        `json:"name"`
	Ext       string        `json:"ext"`
	OrigName  string        `json:"orig_name"`
	Position  sql.NullInt64 `json:"position"`
}

type ProductVariantOption struct {
	VariantID     string `json:"variant_id"`
	OptionValueID string `json:"option_value_id"`
}

type Session struct {
	Key     string         `json:"key"`
	Value   sql.NullString `json:"value"`
	Expires sql.NullInt64  `json:"expires"`
}

type Setting struct {
	ID    string         `json:"id"`
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type Subdomain struct {
	ID   string         `json:"id"`
	Name string         `json:"name"`
	Desc sql.NullString `json:"desc"`
}
