// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package sqlite

import (
	"context"
	"database/sql"
)

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM page
`

func (q *Queries) CountPages(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countPagesStmt, countPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO page (id, name, slug, content, position, active, created)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, name, slug, content, position, active, created, updated
`

type CreatePageParams struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
}

type CreatePageRow struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (CreatePageRow, error) {
	row := q.queryRow(ctx, q.createPageStmt, createPage,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Content,
		arg.Position,
		arg.Active,
	)
	var i CreatePageRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Content,
		&i.Position,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM page WHERE id = ?
`

func (q *Queries) DeletePage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deletePageStmt, deletePage, id)
	return err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, name, slug, content, position, active, created, updated
FROM page WHERE id = ? LIMIT 1
`

type GetPageByIDRow struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
}

func (q *Queries) GetPageByID(ctx context.Context, id string) (GetPageByIDRow, error) {
	row := q.queryRow(ctx, q.getPageByIDStmt, getPageByID, id)
	var i GetPageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Content,
		&i.Position,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, name, slug, content, position, active, created, updated
FROM page WHERE slug = ? LIMIT 1
`

type GetPageBySlugRow struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
}

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (GetPageBySlugRow, error) {
	row := q.queryRow(ctx, q.getPageBySlugStmt, getPageBySlug, slug)
	var i GetPageBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Content,
		&i.Position,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, name, slug, content, position, active, created, updated
FROM page
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListPagesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListPagesRow struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]ListPagesRow, error) {
	rows, err := q.query(ctx, q.listPagesStmt, listPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagesRow{}
	for rows.Next() {
		var i ListPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Content,
			&i.Position,
			&i.Active,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesByPosition = `-- name: ListPagesByPosition :many
SELECT id, name, slug, content, position, active, created, updated
FROM page
WHERE position = ? AND active = ?
ORDER BY created DESC
`

type ListPagesByPositionParams struct {
	Position string `json:"position"`
	Active   bool   `json:"active"`
}

type ListPagesByPositionRow struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
}

func (q *Queries) ListPagesByPosition(ctx context.Context, arg ListPagesByPositionParams) ([]ListPagesByPositionRow, error) {
	rows, err := q.query(ctx, q.listPagesByPositionStmt, listPagesByPosition, arg.Position, arg.Active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPagesByPositionRow{}
	for rows.Next() {
		var i ListPagesByPositionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Content,
			&i.Position,
			&i.Active,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageExists = `-- name: PageExists :one
SELECT EXISTS(SELECT 1 FROM page WHERE slug = ?)
`

func (q *Queries) PageExists(ctx context.Context, slug string) (bool, error) {
	row := q.queryRow(ctx, q.pageExistsStmt, pageExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePage = `-- name: UpdatePage :exec
UPDATE page
SET name = ?, slug = ?, content = ?, position = ?, active = ?, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePageParams struct {
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.exec(ctx, q.updatePageStmt, updatePage,
		arg.Name,
		arg.Slug,
		arg.Content,
		arg.Position,
		arg.Active,
		arg.ID,
	)
	return err
}

const updatePageActive = `-- name: UpdatePageActive :exec
UPDATE page
SET active = NOT active, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdatePageActive(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.updatePageActiveStmt, updatePageActive, id)
	return err
}

const updatePageContent = `-- name: UpdatePageContent :exec
UPDATE page
SET content = ?, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePageContentParams struct {
	Content sql.NullString `json:"content"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdatePageContent(ctx context.Context, arg UpdatePageContentParams) error {
	_, err := q.exec(ctx, q.updatePageContentStmt, updatePageContent, arg.Content, arg.ID)
	return err
}
