// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM product WHERE deleted = FALSE
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countProductsStmt, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (id, name, "desc", slug, amount, metadata, attribute, digital, active, created)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
`

type CreateProductParams struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    interface{}     `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
}

type CreateProductRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    interface{}     `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.ID,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Digital,
		arg.Active,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductStmt, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product WHERE id = ? AND deleted = FALSE LIMIT 1
`

type GetProductByIDRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    interface{}     `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) GetProductByID(ctx context.Context, id string) (GetProductByIDRow, error) {
	row := q.queryRow(ctx, q.getProductByIDStmt, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product WHERE slug = ? AND deleted = FALSE LIMIT 1
`

type GetProductBySlugRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    interface{}     `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.queryRow(ctx, q.getProductBySlugStmt, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE active = TRUE AND deleted = FALSE
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListActiveProductsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListActiveProductsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    interface{}     `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]ListActiveProductsRow, error) {
	rows, err := q.query(ctx, q.listActiveProductsStmt, listActiveProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsRow{}
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE deleted = FALSE
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListProductsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListProductsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    interface{}     `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS(SELECT 1 FROM product WHERE slug = ? AND deleted = FALSE)
`

func (q *Queries) ProductExists(ctx context.Context, slug string) (bool, error) {
	row := q.queryRow(ctx, q.productExistsStmt, productExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE product
SET deleted = TRUE, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.softDeleteProductStmt, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET name = ?, "desc" = ?, slug = ?, amount = ?, metadata = ?, attribute = ?, digital = ?, active = ?, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateProductParams struct {
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    interface{}     `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	ID        string          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.exec(ctx, q.updateProductStmt, updateProduct,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Digital,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateProductActive = `-- name: UpdateProductActive :exec
UPDATE product
SET active = NOT active, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateProductActive(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.updateProductActiveStmt, updateProductActive, id)
	return err
}
