// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countCarts = `-- name: CountCarts :one
SELECT COUNT(*) FROM cart
`

func (q *Queries) CountCarts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countCartsStmt, countCarts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO cart (id, email, amount_total, currency, payment_id, payment_status, cart, payment_system, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id, email, amount_total, currency, payment_id, payment_status, cart, payment_system, created, updated
`

type CreateCartParams struct {
	ID            string          `json:"id"`
	Email         sql.NullString  `json:"email"`
	AmountTotal   string          `json:"amount_total"`
	Currency      string          `json:"currency"`
	PaymentID     sql.NullString  `json:"payment_id"`
	PaymentStatus sql.NullString  `json:"payment_status"`
	Cart          json.RawMessage `json:"cart"`
	PaymentSystem string          `json:"payment_system"`
}

type CreateCartRow struct {
	ID            string          `json:"id"`
	Email         sql.NullString  `json:"email"`
	AmountTotal   string          `json:"amount_total"`
	Currency      string          `json:"currency"`
	PaymentID     sql.NullString  `json:"payment_id"`
	PaymentStatus sql.NullString  `json:"payment_status"`
	Cart          json.RawMessage `json:"cart"`
	PaymentSystem string          `json:"payment_system"`
	Created       sql.NullTime    `json:"created"`
	Updated       sql.NullTime    `json:"updated"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (CreateCartRow, error) {
	row := q.queryRow(ctx, q.createCartStmt, createCart,
		arg.ID,
		arg.Email,
		arg.AmountTotal,
		arg.Currency,
		arg.PaymentID,
		arg.PaymentStatus,
		arg.Cart,
		arg.PaymentSystem,
	)
	var i CreateCartRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.AmountTotal,
		&i.Currency,
		&i.PaymentID,
		&i.PaymentStatus,
		&i.Cart,
		&i.PaymentSystem,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM cart WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteCartStmt, deleteCart, id)
	return err
}

const getCart = `-- name: GetCart :one
SELECT id, email, amount_total, currency, payment_id, payment_status, cart, payment_system, created, updated
FROM cart WHERE id = $1 LIMIT 1
`

type GetCartRow struct {
	ID            string          `json:"id"`
	Email         sql.NullString  `json:"email"`
	AmountTotal   string          `json:"amount_total"`
	Currency      string          `json:"currency"`
	PaymentID     sql.NullString  `json:"payment_id"`
	PaymentStatus sql.NullString  `json:"payment_status"`
	Cart          json.RawMessage `json:"cart"`
	PaymentSystem string          `json:"payment_system"`
	Created       sql.NullTime    `json:"created"`
	Updated       sql.NullTime    `json:"updated"`
}

func (q *Queries) GetCart(ctx context.Context, id string) (GetCartRow, error) {
	row := q.queryRow(ctx, q.getCartStmt, getCart, id)
	var i GetCartRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.AmountTotal,
		&i.Currency,
		&i.PaymentID,
		&i.PaymentStatus,
		&i.Cart,
		&i.PaymentSystem,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listCarts = `-- name: ListCarts :many
SELECT id, email, amount_total, currency, payment_id, payment_status, cart, payment_system, created, updated
FROM cart
ORDER BY created DESC
LIMIT $1 OFFSET $2
`

type ListCartsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCartsRow struct {
	ID            string          `json:"id"`
	Email         sql.NullString  `json:"email"`
	AmountTotal   string          `json:"amount_total"`
	Currency      string          `json:"currency"`
	PaymentID     sql.NullString  `json:"payment_id"`
	PaymentStatus sql.NullString  `json:"payment_status"`
	Cart          json.RawMessage `json:"cart"`
	PaymentSystem string          `json:"payment_system"`
	Created       sql.NullTime    `json:"created"`
	Updated       sql.NullTime    `json:"updated"`
}

func (q *Queries) ListCarts(ctx context.Context, arg ListCartsParams) ([]ListCartsRow, error) {
	rows, err := q.query(ctx, q.listCartsStmt, listCarts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartsRow{}
	for rows.Next() {
		var i ListCartsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AmountTotal,
			&i.Currency,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.Cart,
			&i.PaymentSystem,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCart = `-- name: UpdateCart :exec
UPDATE cart
SET email = $1, amount_total = $2, currency = $3, payment_id = $4, payment_status = $5, cart = $6, payment_system = $7, updated = NOW()
WHERE id = $8
`

type UpdateCartParams struct {
	Email         sql.NullString  `json:"email"`
	AmountTotal   string          `json:"amount_total"`
	Currency      string          `json:"currency"`
	PaymentID     sql.NullString  `json:"payment_id"`
	PaymentStatus sql.NullString  `json:"payment_status"`
	Cart          json.RawMessage `json:"cart"`
	PaymentSystem string          `json:"payment_system"`
	ID            string          `json:"id"`
}

func (q *Queries) UpdateCart(ctx context.Context, arg UpdateCartParams) error {
	_, err := q.exec(ctx, q.updateCartStmt, updateCart,
		arg.Email,
		arg.AmountTotal,
		arg.Currency,
		arg.PaymentID,
		arg.PaymentStatus,
		arg.Cart,
		arg.PaymentSystem,
		arg.ID,
	)
	return err
}

const updateCartPaymentStatus = `-- name: UpdateCartPaymentStatus :exec
UPDATE cart
SET payment_status = $1, updated = NOW()
WHERE id = $2
`

type UpdateCartPaymentStatusParams struct {
	PaymentStatus sql.NullString `json:"payment_status"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateCartPaymentStatus(ctx context.Context, arg UpdateCartPaymentStatusParams) error {
	_, err := q.exec(ctx, q.updateCartPaymentStatusStmt, updateCartPaymentStatus, arg.PaymentStatus, arg.ID)
	return err
}
