// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
)

const bulkDeleteProductImages = `-- name: BulkDeleteProductImages :exec

DELETE FROM product_image
WHERE product_id = $1
`

// Advanced Product Queries
func (q *Queries) BulkDeleteProductImages(ctx context.Context, productID string) error {
	_, err := q.exec(ctx, q.bulkDeleteProductImagesStmt, bulkDeleteProductImages, productID)
	return err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM product WHERE deleted = FALSE
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countProductsStmt, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (id, name, "desc", slug, amount, metadata, attribute, digital, active, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
`

type CreateProductParams struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
}

type CreateProductRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.ID,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Digital,
		arg.Active,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createProductOption = `-- name: CreateProductOption :one
INSERT INTO product_option (id, name, product_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, name, product_id, position, created
`

type CreateProductOptionParams struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	ProductID string        `json:"product_id"`
	Position  sql.NullInt32 `json:"position"`
}

type CreateProductOptionRow struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	ProductID string        `json:"product_id"`
	Position  sql.NullInt32 `json:"position"`
	Created   sql.NullTime  `json:"created"`
}

func (q *Queries) CreateProductOption(ctx context.Context, arg CreateProductOptionParams) (CreateProductOptionRow, error) {
	row := q.queryRow(ctx, q.createProductOptionStmt, createProductOption,
		arg.ID,
		arg.Name,
		arg.ProductID,
		arg.Position,
	)
	var i CreateProductOptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProductID,
		&i.Position,
		&i.Created,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variant (id, product_id, sku, price_surcharge, quantity, option_values)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, sku, price_surcharge, quantity, option_values, active, deleted, created, updated
`

type CreateProductVariantParams struct {
	ID             string         `json:"id"`
	ProductID      string         `json:"product_id"`
	Sku            sql.NullString `json:"sku"`
	PriceSurcharge sql.NullString `json:"price_surcharge"`
	Quantity       sql.NullInt32  `json:"quantity"`
	OptionValues   string         `json:"option_values"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.queryRow(ctx, q.createProductVariantStmt, createProductVariant,
		arg.ID,
		arg.ProductID,
		arg.Sku,
		arg.PriceSurcharge,
		arg.Quantity,
		arg.OptionValues,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.PriceSurcharge,
		&i.Quantity,
		&i.OptionValues,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductStmt, deleteProduct, id)
	return err
}

const deleteProductOption = `-- name: DeleteProductOption :exec
DELETE FROM product_option WHERE id = $1
`

func (q *Queries) DeleteProductOption(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductOptionStmt, deleteProductOption, id)
	return err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variant WHERE id = $1
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductVariantStmt, deleteProductVariant, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product WHERE id = $1 AND deleted = FALSE LIMIT 1
`

type GetProductByIDRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) GetProductByID(ctx context.Context, id string) (GetProductByIDRow, error) {
	row := q.queryRow(ctx, q.getProductByIDStmt, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product WHERE slug = $1 AND deleted = FALSE LIMIT 1
`

type GetProductBySlugRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.queryRow(ctx, q.getProductBySlugStmt, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductOption = `-- name: GetProductOption :one
SELECT id, name, product_id, position, created
FROM product_option
WHERE id = $1 LIMIT 1
`

type GetProductOptionRow struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	ProductID string        `json:"product_id"`
	Position  sql.NullInt32 `json:"position"`
	Created   sql.NullTime  `json:"created"`
}

func (q *Queries) GetProductOption(ctx context.Context, id string) (GetProductOptionRow, error) {
	row := q.queryRow(ctx, q.getProductOptionStmt, getProductOption, id)
	var i GetProductOptionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProductID,
		&i.Position,
		&i.Created,
	)
	return i, err
}

const getProductWithVariants = `-- name: GetProductWithVariants :many

SELECT
    p.id as product_id,
    p.name as product_name,
    pv.id as variant_id,
    pv.sku as variant_sku,
    pv.price_surcharge as variant_price_surcharge,
    pv.quantity as variant_quantity,
    pv.option_values as variant_option_values
FROM product p
LEFT JOIN product_variant pv ON p.id = pv.product_id
WHERE p.id = $1
`

type GetProductWithVariantsRow struct {
	ProductID             string         `json:"product_id"`
	ProductName           string         `json:"product_name"`
	VariantID             sql.NullString `json:"variant_id"`
	VariantSku            sql.NullString `json:"variant_sku"`
	VariantPriceSurcharge sql.NullString `json:"variant_price_surcharge"`
	VariantQuantity       sql.NullInt32  `json:"variant_quantity"`
	VariantOptionValues   sql.NullString `json:"variant_option_values"`
}

// Product Variant Queries
func (q *Queries) GetProductWithVariants(ctx context.Context, id string) ([]GetProductWithVariantsRow, error) {
	rows, err := q.query(ctx, q.getProductWithVariantsStmt, getProductWithVariants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductWithVariantsRow{}
	for rows.Next() {
		var i GetProductWithVariantsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.VariantID,
			&i.VariantSku,
			&i.VariantPriceSurcharge,
			&i.VariantQuantity,
			&i.VariantOptionValues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithImages = `-- name: GetProductsWithImages :many
SELECT
    p.id as product_id,
    p.name as product_name,
    pi.id as image_id,
    pi.name as image_name,
    pi.ext as image_ext
FROM product p
LEFT JOIN product_image pi ON p.id = pi.product_id
WHERE p.active = TRUE AND p.deleted = FALSE
ORDER BY p.created DESC
`

type GetProductsWithImagesRow struct {
	ProductID   string         `json:"product_id"`
	ProductName string         `json:"product_name"`
	ImageID     sql.NullString `json:"image_id"`
	ImageName   sql.NullString `json:"image_name"`
	ImageExt    sql.NullString `json:"image_ext"`
}

func (q *Queries) GetProductsWithImages(ctx context.Context) ([]GetProductsWithImagesRow, error) {
	rows, err := q.query(ctx, q.getProductsWithImagesStmt, getProductsWithImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsWithImagesRow{}
	for rows.Next() {
		var i GetProductsWithImagesRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ImageID,
			&i.ImageName,
			&i.ImageExt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE active = TRUE AND deleted = FALSE
ORDER BY created DESC
LIMIT $1 OFFSET $2
`

type ListActiveProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListActiveProductsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]ListActiveProductsRow, error) {
	rows, err := q.query(ctx, q.listActiveProductsStmt, listActiveProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsRow{}
	for rows.Next() {
		var i ListActiveProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsByProduct = `-- name: ListProductVariantsByProduct :many
SELECT id, product_id, sku, price_surcharge, quantity, option_values, active, deleted, created, updated
FROM product_variant
WHERE product_id = $1
`

func (q *Queries) ListProductVariantsByProduct(ctx context.Context, productID string) ([]ProductVariant, error) {
	rows, err := q.query(ctx, q.listProductVariantsByProductStmt, listProductVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.PriceSurcharge,
			&i.Quantity,
			&i.OptionValues,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, "desc", slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE deleted = FALSE
ORDER BY created DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productExists = `-- name: ProductExists :one
SELECT EXISTS(SELECT 1 FROM product WHERE slug = $1 AND deleted = FALSE)
`

func (q *Queries) ProductExists(ctx context.Context, slug string) (bool, error) {
	row := q.queryRow(ctx, q.productExistsStmt, productExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE product
SET deleted = TRUE, updated = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.softDeleteProductStmt, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET name = $1, "desc" = $2, slug = $3, amount = $4, metadata = $5, attribute = $6, digital = $7, active = $8, updated = NOW()
WHERE id = $9
`

type UpdateProductParams struct {
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    string          `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	ID        string          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.exec(ctx, q.updateProductStmt, updateProduct,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Digital,
		arg.Active,
		arg.ID,
	)
	return err
}

const updateProductActive = `-- name: UpdateProductActive :exec
UPDATE product
SET active = NOT active, updated = NOW()
WHERE id = $1
`

func (q *Queries) UpdateProductActive(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.updateProductActiveStmt, updateProductActive, id)
	return err
}

const updateProductVariant = `-- name: UpdateProductVariant :exec
UPDATE product_variant
SET sku = $2, price_surcharge = $3, quantity = $4, option_values = $5, updated = NOW()
WHERE id = $1
`

type UpdateProductVariantParams struct {
	ID             string         `json:"id"`
	Sku            sql.NullString `json:"sku"`
	PriceSurcharge sql.NullString `json:"price_surcharge"`
	Quantity       sql.NullInt32  `json:"quantity"`
	OptionValues   string         `json:"option_values"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) error {
	_, err := q.exec(ctx, q.updateProductVariantStmt, updateProductVariant,
		arg.ID,
		arg.Sku,
		arg.PriceSurcharge,
		arg.Quantity,
		arg.OptionValues,
	)
	return err
}
