// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package postgres

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session (key, value, expires) VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	Key     string         `json:"key"`
	Value   sql.NullString `json:"value"`
	Expires sql.NullInt32  `json:"expires"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.exec(ctx, q.createSessionStmt, createSession, arg.Key, arg.Value, arg.Expires)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expires sql.NullInt32) error {
	_, err := q.exec(ctx, q.deleteExpiredSessionsStmt, deleteExpiredSessions, expires)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE key = $1
`

func (q *Queries) DeleteSession(ctx context.Context, key string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, key)
	return err
}

const getSession = `-- name: GetSession :one
SELECT key, value, expires FROM session WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, key string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionStmt, getSession, key)
	var i Session
	err := row.Scan(&i.Key, &i.Value, &i.Expires)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE session SET value = $1, expires = $2 WHERE key = $3
`

type UpdateSessionParams struct {
	Value   sql.NullString `json:"value"`
	Expires sql.NullInt32  `json:"expires"`
	Key     string         `json:"key"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.exec(ctx, q.updateSessionStmt, updateSession, arg.Value, arg.Expires, arg.Key)
	return err
}
