// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package postgres

import (
	"context"
	"database/sql"
)

const createSetting = `-- name: CreateSetting :one
INSERT INTO setting (id, key, value)
VALUES ($1, $2, $3)
RETURNING id, key, value
`

type CreateSettingParams struct {
	ID    string         `json:"id"`
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error) {
	row := q.queryRow(ctx, q.createSettingStmt, createSetting, arg.ID, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM setting WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.exec(ctx, q.deleteSettingStmt, deleteSetting, key)
	return err
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT id, key, value
FROM setting
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (Setting, error) {
	row := q.queryRow(ctx, q.getSettingByKeyStmt, getSettingByKey, key)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT id, key, value
FROM setting
ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.query(ctx, q.listSettingsStmt, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.ID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE setting
SET value = $1
WHERE key = $2
`

type UpdateSettingParams struct {
	Value sql.NullString `json:"value"`
	Key   string         `json:"key"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.exec(ctx, q.updateSettingStmt, updateSetting, arg.Value, arg.Key)
	return err
}
