// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subdomains.sql

package postgres

import (
	"context"
	"database/sql"
)

const createSubdomain = `-- name: CreateSubdomain :one
INSERT INTO subdomain (id, name, "desc")
VALUES ($1, $2, $3)
RETURNING id, name, "desc"
`

type CreateSubdomainParams struct {
	ID   string         `json:"id"`
	Name string         `json:"name"`
	Desc sql.NullString `json:"desc"`
}

func (q *Queries) CreateSubdomain(ctx context.Context, arg CreateSubdomainParams) (Subdomain, error) {
	row := q.queryRow(ctx, q.createSubdomainStmt, createSubdomain, arg.ID, arg.Name, arg.Desc)
	var i Subdomain
	err := row.Scan(&i.ID, &i.Name, &i.Desc)
	return i, err
}

const deleteSubdomain = `-- name: DeleteSubdomain :exec
DELETE FROM subdomain WHERE id = $1
`

func (q *Queries) DeleteSubdomain(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSubdomainStmt, deleteSubdomain, id)
	return err
}

const getSubdomain = `-- name: GetSubdomain :one
SELECT id, name, "desc"
FROM subdomain WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubdomain(ctx context.Context, id string) (Subdomain, error) {
	row := q.queryRow(ctx, q.getSubdomainStmt, getSubdomain, id)
	var i Subdomain
	err := row.Scan(&i.ID, &i.Name, &i.Desc)
	return i, err
}

const getSubdomainByName = `-- name: GetSubdomainByName :one
SELECT id, name, "desc"
FROM subdomain WHERE name = $1 LIMIT 1
`

func (q *Queries) GetSubdomainByName(ctx context.Context, name string) (Subdomain, error) {
	row := q.queryRow(ctx, q.getSubdomainByNameStmt, getSubdomainByName, name)
	var i Subdomain
	err := row.Scan(&i.ID, &i.Name, &i.Desc)
	return i, err
}

const listSubdomains = `-- name: ListSubdomains :many
SELECT id, name, "desc"
FROM subdomain
ORDER BY name
`

func (q *Queries) ListSubdomains(ctx context.Context) ([]Subdomain, error) {
	rows, err := q.query(ctx, q.listSubdomainsStmt, listSubdomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subdomain{}
	for rows.Next() {
		var i Subdomain
		if err := rows.Scan(&i.ID, &i.Name, &i.Desc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subdomainExists = `-- name: SubdomainExists :one
SELECT EXISTS(SELECT 1 FROM subdomain WHERE name = $1)
`

func (q *Queries) SubdomainExists(ctx context.Context, name string) (bool, error) {
	row := q.queryRow(ctx, q.subdomainExistsStmt, subdomainExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSubdomain = `-- name: UpdateSubdomain :exec
UPDATE subdomain
SET name = $1, "desc" = $2
WHERE id = $3
`

type UpdateSubdomainParams struct {
	Name string         `json:"name"`
	Desc sql.NullString `json:"desc"`
	ID   string         `json:"id"`
}

func (q *Queries) UpdateSubdomain(ctx context.Context, arg UpdateSubdomainParams) error {
	_, err := q.exec(ctx, q.updateSubdomainStmt, updateSubdomain, arg.Name, arg.Desc, arg.ID)
	return err
}
