// @title           myCart API
// @version         1.0
// @description     Open source shopping-cart backend API - a single-binary e-commerce solution
// @termsOfService  https://github.com/shurco/mycart

// @contact.name   API Support
// @contact.url    https://github.com/shurco/mycart/issues
// @contact.email  support@mycart.com

// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	app "github.com/shurco/mycart/internal"
	"github.com/shurco/mycart/internal/models"
	"github.com/shurco/mycart/pkg/update"

	// Swagger docs auto-generated by swag init
	// _ "github.com/shurco/mycart/docs/swagger"
)

var (
	version   = "v0.0.1"
	gitCommit = "00000000"
	buildDate = "14.07.2023"
)

var rootCmd = &cobra.Command{
	Use:                "mycart",
	Short:              "myCart CLI",
	Long:               "🛒 myCart - shopping-cart in 1 file",
	Version:            fmt.Sprintf("myCart %s (%s) from %s", version, gitCommit, buildDate),
	FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
	CompletionOptions:  cobra.CompletionOptions{DisableDefaultCmd: true},
}

func main() {
	update.SetVersion(&update.Version{
		CurrentVersion: version,
		GitCommit:      gitCommit,
		BuildDate:      buildDate,
	})

	rootCmd.SetHelpCommand(&cobra.Command{
		Use:    "no-help",
		Hidden: true,
	})

	rootCmd.AddCommand(cmdInit())
	rootCmd.AddCommand(cmdInstall())
	rootCmd.AddCommand(cmdServe())
	rootCmd.AddCommand(cmdUpdate())
	rootCmd.AddCommand(cmdMigrate())
	rootCmd.AddCommand(cmdMigrateToPostgres())
	rootCmd.AddCommand(cmdMigrateToSQLite())

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

// handleCommandError handles command execution errors uniformly.
func handleCommandError(err error) {
	if err != nil {
		fmt.Print(err)
		os.Exit(1)
	}
}

// cmdServe creates and returns the serve command.
func cmdServe() *cobra.Command {
	var noSite, devMode bool
	var httpAddr, httpsAddr string

	cmd := &cobra.Command{
		Use:   "serve [flags]",
		Short: "Starts the web server (default to 0.0.0.0:8080)",
		Run: func(_ *cobra.Command, _ []string) {
			handleCommandError(app.NewApp(httpAddr, httpsAddr, noSite, devMode))
		},
	}

	cmd.PersistentFlags().StringVar(&httpAddr, "http", "0.0.0.0:8080", "server address")
	cmd.PersistentFlags().StringVar(&httpsAddr, "https", "", "https server address (auto TLS)")
	cmd.PersistentFlags().BoolVar(&noSite, "no-site", false, "disable create site")
	cmd.PersistentFlags().BoolVar(&devMode, "dev", false, "develop mode")

	if err := cmd.PersistentFlags().MarkHidden("dev"); err != nil {
		fmt.Println("warning: failed to hide dev flag:", err)
	}

	return cmd
}

// cmdInstall creates and returns the install command.
func cmdInstall() *cobra.Command {
	var email, password, domain string
	var dbType, databaseURL, dbHost, dbName, dbUser, dbPassword, dbSSLMode string
	var dbPort int

	cmd := &cobra.Command{
		Use:   "install",
		Short: "Create the admin account (first-time setup)",
		Long: `Create the admin account and initialize the database.

Database options:
  SQLite (default):    --db-type=sqlite
  PostgreSQL:          --db-type=postgresql --database-url="postgresql://..."
  PostgreSQL (manual): --db-type=postgresql --db-host=localhost --db-port=5432 --db-name=mycart --db-user=postgres --db-password=secret`,
		Run: func(_ *cobra.Command, _ []string) {
			// Set database environment variables if provided
			if dbType != "" {
				os.Setenv("DB_TYPE", dbType)
			}
			if databaseURL != "" {
				os.Setenv("DATABASE_URL", databaseURL)
			}
			if dbHost != "" {
				os.Setenv("DB_HOST", dbHost)
			}
			if dbPort > 0 {
				os.Setenv("DB_PORT", fmt.Sprintf("%d", dbPort))
			}
			if dbName != "" {
				os.Setenv("DB_NAME", dbName)
			}
			if dbUser != "" {
				os.Setenv("DB_USER", dbUser)
			}
			if dbPassword != "" {
				os.Setenv("DB_PASSWORD", dbPassword)
			}
			if dbSSLMode != "" {
				os.Setenv("DB_SSLMODE", dbSSLMode)
			}

			handleCommandError(app.InstallAdmin(context.Background(), &models.Install{
				Email:    email,
				Password: password,
				Domain:   domain,
			}))
			fmt.Println("Cart installed successfully")
		},
	}

	// Admin credentials
	cmd.Flags().StringVar(&email, "email", "", "admin email address")
	cmd.Flags().StringVar(&password, "password", "", "admin password (6-72 chars)")
	cmd.Flags().StringVar(&domain, "domain", "localhost", "public store domain")
	_ = cmd.MarkFlagRequired("email")
	_ = cmd.MarkFlagRequired("password")

	// Database configuration
	cmd.Flags().StringVar(&dbType, "db-type", "", "database type: sqlite (default) or postgresql")
	cmd.Flags().StringVar(&databaseURL, "database-url", "", "PostgreSQL connection URL (e.g., postgresql://user:pass@host:5432/db)")
	cmd.Flags().StringVar(&dbHost, "db-host", "", "database host")
	cmd.Flags().IntVar(&dbPort, "db-port", 0, "database port")
	cmd.Flags().StringVar(&dbName, "db-name", "", "database name")
	cmd.Flags().StringVar(&dbUser, "db-user", "", "database user")
	cmd.Flags().StringVar(&dbPassword, "db-password", "", "database password")
	cmd.Flags().StringVar(&dbSSLMode, "db-sslmode", "", "PostgreSQL SSL mode: disable, require, verify-ca, verify-full")

	return cmd
}

// cmdInit creates and returns the init command.
func cmdInit() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Creating the basic structure",
		Run: func(_ *cobra.Command, _ []string) {
			handleCommandError(app.Init())
		},
	}
}

// cmdUpdate creates and returns the update command.
func cmdUpdate() *cobra.Command {
	return &cobra.Command{
		Use:   "update",
		Short: "Updating the application to the latest version",
		Run: func(_ *cobra.Command, _ []string) {
			cfg := &update.Config{
				Owner:             "shurco",
				Repo:              "mycart",
				CurrentVersion:    version,
				ArchiveExecutable: "mycart",
			}

			if err := update.Init(cfg); err != nil {
				handleCommandError(err)
				return
			}

			handleCommandError(app.Migrate())
		},
	}
}

// cmdMigrate creates and returns the migrate command.
func cmdMigrate() *cobra.Command {
	return &cobra.Command{
		Use:   "migrate",
		Short: "Migrate on the latest version of database schema",
		Run: func(_ *cobra.Command, _ []string) {
			handleCommandError(app.Migrate())
		},
	}
}

// cmdMigrateToPostgres creates and returns the migrate-to-postgres command.
func cmdMigrateToPostgres() *cobra.Command {
	var databaseURL, dbHost, dbName, dbUser, dbPassword, dbSSLMode string
	var dbPort int

	cmd := &cobra.Command{
		Use:   "migrate-to-postgres",
		Short: "Migrate data from SQLite to PostgreSQL",
		Long: `Migrate all data from SQLite database to PostgreSQL.

This command will:
1. Create a backup of the SQLite database
2. Connect to the target PostgreSQL database
3. Copy all data from SQLite to PostgreSQL
4. Verify the migration

Example:
  mycart migrate-to-postgres --database-url="postgresql://user:pass@localhost:5432/mycart"`,
		Run: func(_ *cobra.Command, _ []string) {
			// Set PostgreSQL environment variables
			if databaseURL != "" {
				os.Setenv("DATABASE_URL", databaseURL)
			}
			if dbHost != "" {
				os.Setenv("DB_HOST", dbHost)
			}
			if dbPort > 0 {
				os.Setenv("DB_PORT", fmt.Sprintf("%d", dbPort))
			}
			if dbName != "" {
				os.Setenv("DB_NAME", dbName)
			}
			if dbUser != "" {
				os.Setenv("DB_USER", dbUser)
			}
			if dbPassword != "" {
				os.Setenv("DB_PASSWORD", dbPassword)
			}
			if dbSSLMode != "" {
				os.Setenv("DB_SSLMODE", dbSSLMode)
			}

			handleCommandError(app.MigrateToPostgres())
		},
	}

	cmd.Flags().StringVar(&databaseURL, "database-url", "", "PostgreSQL connection URL (required)")
	cmd.Flags().StringVar(&dbHost, "db-host", "", "database host")
	cmd.Flags().IntVar(&dbPort, "db-port", 5432, "database port")
	cmd.Flags().StringVar(&dbName, "db-name", "", "database name")
	cmd.Flags().StringVar(&dbUser, "db-user", "", "database user")
	cmd.Flags().StringVar(&dbPassword, "db-password", "", "database password")
	cmd.Flags().StringVar(&dbSSLMode, "db-sslmode", "require", "PostgreSQL SSL mode")

	return cmd
}

// cmdMigrateToSQLite creates and returns the migrate-to-sqlite command.
func cmdMigrateToSQLite() *cobra.Command {
	var sqlitePath string

	cmd := &cobra.Command{
		Use:   "migrate-to-sqlite",
		Short: "Migrate data from PostgreSQL to SQLite",
		Long: `Migrate all data from PostgreSQL database to SQLite.

This command will:
1. Create a new SQLite database
2. Connect to the source PostgreSQL database
3. Copy all data from PostgreSQL to SQLite
4. Verify the migration

Example:
  mycart migrate-to-sqlite --path=./lc_base/data.db`,
		Run: func(_ *cobra.Command, _ []string) {
			if sqlitePath != "" {
				os.Setenv("SQLITE_PATH", sqlitePath)
			}

			handleCommandError(app.MigrateToSQLite())
		},
	}

	cmd.Flags().StringVar(&sqlitePath, "path", "./lc_base/data.db", "SQLite database file path")

	return cmd
}
