// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getAuthCredentials = `-- name: GetAuthCredentials :one
SELECT key, value
FROM setting
WHERE key IN ('email', 'password')
LIMIT 2
`

type GetAuthCredentialsRow struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) GetAuthCredentials(ctx context.Context) (GetAuthCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthCredentials)
	var i GetAuthCredentialsRow
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const getEmailSetting = `-- name: GetEmailSetting :one
SELECT id, key, value
FROM setting
WHERE key = 'email'
LIMIT 1
`

func (q *Queries) GetEmailSetting(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getEmailSetting)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}

const getPasswordSetting = `-- name: GetPasswordSetting :one
SELECT id, key, value
FROM setting
WHERE key = 'password'
LIMIT 1
`

func (q *Queries) GetPasswordSetting(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getPasswordSetting)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE setting
SET value = ?
WHERE key = 'password'
`

func (q *Queries) UpdatePassword(ctx context.Context, value sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updatePassword, value)
	return err
}
