// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countCarts = `-- name: CountCarts :one
SELECT COUNT(*) as count
FROM cart
`

func (q *Queries) CountCarts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCarts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCart = `-- name: CreateCart :exec
INSERT INTO cart (id, email, amount_total, currency, payment_system, created)
VALUES (?, ?, ?, ?, ?, datetime('now'))
`

type CreateCartParams struct {
	ID            string         `json:"id"`
	Email         sql.NullString `json:"email"`
	AmountTotal   float64        `json:"amount_total"`
	Currency      string         `json:"currency"`
	PaymentSystem string         `json:"payment_system"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) error {
	_, err := q.db.ExecContext(ctx, createCart,
		arg.ID,
		arg.Email,
		arg.AmountTotal,
		arg.Currency,
		arg.PaymentSystem,
	)
	return err
}

const createCartProduct = `-- name: CreateCartProduct :exec
INSERT INTO cart_product (id, cart_id, product_id, quantity, amount)
VALUES (?, ?, ?, ?, ?)
`

type CreateCartProductParams struct {
	ID        string          `json:"id"`
	CartID    string          `json:"cart_id"`
	ProductID string          `json:"product_id"`
	Quantity  sql.NullFloat64 `json:"quantity"`
	Amount    sql.NullFloat64 `json:"amount"`
}

func (q *Queries) CreateCartProduct(ctx context.Context, arg CreateCartProductParams) error {
	_, err := q.db.ExecContext(ctx, createCartProduct,
		arg.ID,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.Amount,
	)
	return err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM cart
WHERE id = ?
`

func (q *Queries) DeleteCart(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCart, id)
	return err
}

const deleteCartProduct = `-- name: DeleteCartProduct :exec
DELETE FROM cart_product
WHERE id = ?
`

func (q *Queries) DeleteCartProduct(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCartProduct, id)
	return err
}

const deleteCartProducts = `-- name: DeleteCartProducts :exec
DELETE FROM cart_product
WHERE cart_id = ?
`

func (q *Queries) DeleteCartProducts(ctx context.Context, cartID string) error {
	_, err := q.db.ExecContext(ctx, deleteCartProducts, cartID)
	return err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, email, amount_total, currency, payment_id, payment_status, payment_system, created, updated
FROM cart
WHERE id = ?
LIMIT 1
`

// Cart queries
func (q *Queries) GetCartByID(ctx context.Context, id string) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.AmountTotal,
		&i.Currency,
		&i.PaymentID,
		&i.PaymentStatus,
		&i.PaymentSystem,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getCartProductByCartAndProduct = `-- name: GetCartProductByCartAndProduct :one
SELECT id, cart_id, product_id, quantity, amount
FROM cart_product
WHERE cart_id = ? AND product_id = ?
LIMIT 1
`

type GetCartProductByCartAndProductParams struct {
	CartID    string `json:"cart_id"`
	ProductID string `json:"product_id"`
}

func (q *Queries) GetCartProductByCartAndProduct(ctx context.Context, arg GetCartProductByCartAndProductParams) (CartProduct, error) {
	row := q.db.QueryRowContext(ctx, getCartProductByCartAndProduct, arg.CartID, arg.ProductID)
	var i CartProduct
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Amount,
	)
	return i, err
}

const getCartProductByID = `-- name: GetCartProductByID :one
SELECT id, cart_id, product_id, quantity, amount
FROM cart_product
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCartProductByID(ctx context.Context, id string) (CartProduct, error) {
	row := q.db.QueryRowContext(ctx, getCartProductByID, id)
	var i CartProduct
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.Amount,
	)
	return i, err
}

const getCartProducts = `-- name: GetCartProducts :many
SELECT id, cart_id, product_id, quantity, amount
FROM cart_product
WHERE cart_id = ?
ORDER BY id
`

// Cart Product queries
func (q *Queries) GetCartProducts(ctx context.Context, cartID string) ([]CartProduct, error) {
	rows, err := q.db.QueryContext(ctx, getCartProducts, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartProduct{}
	for rows.Next() {
		var i CartProduct
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCarts = `-- name: ListCarts :many
SELECT id, email, amount_total, currency, payment_id, payment_status, payment_system, created, updated
FROM cart
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListCartsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCarts(ctx context.Context, arg ListCartsParams) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, listCarts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AmountTotal,
			&i.Currency,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentSystem,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsByPaymentSystem = `-- name: ListCartsByPaymentSystem :many
SELECT id, email, amount_total, currency, payment_id, payment_status, payment_system, created, updated
FROM cart
WHERE payment_system = ?
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListCartsByPaymentSystemParams struct {
	PaymentSystem string `json:"payment_system"`
	Limit         int64  `json:"limit"`
	Offset        int64  `json:"offset"`
}

func (q *Queries) ListCartsByPaymentSystem(ctx context.Context, arg ListCartsByPaymentSystemParams) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, listCartsByPaymentSystem, arg.PaymentSystem, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AmountTotal,
			&i.Currency,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentSystem,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsWithPaymentStatus = `-- name: ListCartsWithPaymentStatus :many
SELECT id, email, amount_total, currency, payment_id, payment_status, payment_system, created, updated
FROM cart
WHERE payment_status = ?
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListCartsWithPaymentStatusParams struct {
	PaymentStatus sql.NullString `json:"payment_status"`
	Limit         int64          `json:"limit"`
	Offset        int64          `json:"offset"`
}

// Payment queries
func (q *Queries) ListCartsWithPaymentStatus(ctx context.Context, arg ListCartsWithPaymentStatusParams) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, listCartsWithPaymentStatus, arg.PaymentStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.AmountTotal,
			&i.Currency,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.PaymentSystem,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartPayment = `-- name: UpdateCartPayment :exec
UPDATE cart
SET payment_id = ?,
    payment_status = ?,
    updated = datetime('now')
WHERE id = ?
`

type UpdateCartPaymentParams struct {
	PaymentID     sql.NullString `json:"payment_id"`
	PaymentStatus sql.NullString `json:"payment_status"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateCartPayment(ctx context.Context, arg UpdateCartPaymentParams) error {
	_, err := q.db.ExecContext(ctx, updateCartPayment, arg.PaymentID, arg.PaymentStatus, arg.ID)
	return err
}

const updateCartProductQuantity = `-- name: UpdateCartProductQuantity :exec
UPDATE cart_product
SET quantity = ?,
    amount = ?
WHERE id = ?
`

type UpdateCartProductQuantityParams struct {
	Quantity sql.NullFloat64 `json:"quantity"`
	Amount   sql.NullFloat64 `json:"amount"`
	ID       string          `json:"id"`
}

func (q *Queries) UpdateCartProductQuantity(ctx context.Context, arg UpdateCartProductQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateCartProductQuantity, arg.Quantity, arg.Amount, arg.ID)
	return err
}

const updateCartTotal = `-- name: UpdateCartTotal :exec
UPDATE cart
SET amount_total = ?,
    updated = datetime('now')
WHERE id = ?
`

type UpdateCartTotalParams struct {
	AmountTotal float64 `json:"amount_total"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateCartTotal(ctx context.Context, arg UpdateCartTotalParams) error {
	_, err := q.db.ExecContext(ctx, updateCartTotal, arg.AmountTotal, arg.ID)
	return err
}
