// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type Cart struct {
	ID            string         `json:"id"`
	Email         sql.NullString `json:"email"`
	AmountTotal   float64        `json:"amount_total"`
	Currency      string         `json:"currency"`
	PaymentID     sql.NullString `json:"payment_id"`
	PaymentStatus sql.NullString `json:"payment_status"`
	PaymentSystem string         `json:"payment_system"`
	Created       sql.NullTime   `json:"created"`
	Updated       sql.NullTime   `json:"updated"`
}

type CartProduct struct {
	ID        string          `json:"id"`
	CartID    string          `json:"cart_id"`
	ProductID string          `json:"product_id"`
	Quantity  sql.NullFloat64 `json:"quantity"`
	Amount    sql.NullFloat64 `json:"amount"`
}

type DigitalDatum struct {
	ID        string         `json:"id"`
	ProductID string         `json:"product_id"`
	Content   string         `json:"content"`
	CartID    sql.NullString `json:"cart_id"`
}

type DigitalFile struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

type Page struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	Created  sql.NullTime   `json:"created"`
	Updated  sql.NullTime   `json:"updated"`
}

type Product struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    float64         `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
	Deleted   bool            `json:"deleted"`
	Created   sql.NullTime    `json:"created"`
	Updated   sql.NullTime    `json:"updated"`
}

type ProductImage struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

type Session struct {
	Key     string         `json:"key"`
	Value   sql.NullString `json:"value"`
	Expires sql.NullInt64  `json:"expires"`
}

type Setting struct {
	ID    string         `json:"id"`
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type Subdomain struct {
	ID   string         `json:"id"`
	Name string         `json:"name"`
	Desc sql.NullString `json:"desc"`
}
