// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const checkSlugExists = `-- name: CheckSlugExists :one
SELECT COUNT(*) as count
FROM page
WHERE slug = ? AND id != ?
`

type CheckSlugExistsParams struct {
	Slug string `json:"slug"`
	ID   string `json:"id"`
}

func (q *Queries) CheckSlugExists(ctx context.Context, arg CheckSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSlugExists, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :exec
INSERT INTO page (id, name, slug, content, position, active, created)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreatePageParams struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	Slug     string         `json:"slug"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Content,
		arg.Position,
		arg.Active,
	)
	return err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM page
WHERE id = ?
`

func (q *Queries) DeletePage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, name, slug, content, position, active, created, updated
FROM page
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPageByID(ctx context.Context, id string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Content,
		&i.Position,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, name, slug, content, position, active, created, updated
FROM page
WHERE slug = ?
LIMIT 1
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Content,
		&i.Position,
		&i.Active,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, name, slug, content, position, active, created, updated
FROM page
WHERE active = ?
ORDER BY name
`

func (q *Queries) ListPages(ctx context.Context, active bool) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPages, active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Content,
			&i.Position,
			&i.Active,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesByPosition = `-- name: ListPagesByPosition :many
SELECT id, name, slug, content, position, active, created, updated
FROM page
WHERE position = ? AND active = ?
ORDER BY name
`

type ListPagesByPositionParams struct {
	Position string `json:"position"`
	Active   bool   `json:"active"`
}

func (q *Queries) ListPagesByPosition(ctx context.Context, arg ListPagesByPositionParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPagesByPosition, arg.Position, arg.Active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Content,
			&i.Position,
			&i.Active,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :exec
UPDATE page
SET name = ?,
    content = ?,
    position = ?,
    active = ?,
    updated = datetime('now')
WHERE id = ?
`

type UpdatePageParams struct {
	Name     string         `json:"name"`
	Content  sql.NullString `json:"content"`
	Position string         `json:"position"`
	Active   bool           `json:"active"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage,
		arg.Name,
		arg.Content,
		arg.Position,
		arg.Active,
		arg.ID,
	)
	return err
}
