// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const checkProductSlugExists = `-- name: CheckProductSlugExists :one
SELECT COUNT(*) as count
FROM product
WHERE slug = ? AND id != ? AND deleted = 0
`

type CheckProductSlugExistsParams struct {
	Slug string `json:"slug"`
	ID   string `json:"id"`
}

func (q *Queries) CheckProductSlugExists(ctx context.Context, arg CheckProductSlugExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkProductSlugExists, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveProducts = `-- name: CountActiveProducts :one
SELECT COUNT(*) as count
FROM product
WHERE active = 1 AND deleted = 0
`

func (q *Queries) CountActiveProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProducts = `-- name: CountAllProducts :one
SELECT COUNT(*) as count
FROM product
WHERE deleted = 0
`

func (q *Queries) CountAllProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDigitalData = `-- name: CreateDigitalData :exec
INSERT INTO digital_data (id, product_id, content, cart_id)
VALUES (?, ?, ?, ?)
`

type CreateDigitalDataParams struct {
	ID        string         `json:"id"`
	ProductID string         `json:"product_id"`
	Content   string         `json:"content"`
	CartID    sql.NullString `json:"cart_id"`
}

func (q *Queries) CreateDigitalData(ctx context.Context, arg CreateDigitalDataParams) error {
	_, err := q.db.ExecContext(ctx, createDigitalData,
		arg.ID,
		arg.ProductID,
		arg.Content,
		arg.CartID,
	)
	return err
}

const createDigitalFile = `-- name: CreateDigitalFile :exec
INSERT INTO digital_file (id, product_id, name, ext, orig_name)
VALUES (?, ?, ?, ?, ?)
`

type CreateDigitalFileParams struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

func (q *Queries) CreateDigitalFile(ctx context.Context, arg CreateDigitalFileParams) error {
	_, err := q.db.ExecContext(ctx, createDigitalFile,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Ext,
		arg.OrigName,
	)
	return err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO product (id, name, desc, slug, amount, metadata, attribute, digital, active, created)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateProductParams struct {
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Slug      string          `json:"slug"`
	Amount    float64         `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Digital   sql.NullString  `json:"digital"`
	Active    bool            `json:"active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Desc,
		arg.Slug,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Digital,
		arg.Active,
	)
	return err
}

const createProductImage = `-- name: CreateProductImage :exec
INSERT INTO product_image (id, product_id, name, ext, orig_name)
VALUES (?, ?, ?, ?, ?)
`

type CreateProductImageParams struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) error {
	_, err := q.db.ExecContext(ctx, createProductImage,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Ext,
		arg.OrigName,
	)
	return err
}

const deleteDigitalFile = `-- name: DeleteDigitalFile :exec
DELETE FROM digital_file
WHERE id = ?
`

func (q *Queries) DeleteDigitalFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDigitalFile, id)
	return err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_image
WHERE id = ?
`

func (q *Queries) DeleteProductImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProductImage, id)
	return err
}

const deleteProductImages = `-- name: DeleteProductImages :exec
DELETE FROM product_image
WHERE product_id = ?
`

func (q *Queries) DeleteProductImages(ctx context.Context, productID string) error {
	_, err := q.db.ExecContext(ctx, deleteProductImages, productID)
	return err
}

const getDigitalData = `-- name: GetDigitalData :one
SELECT id, product_id, content, cart_id
FROM digital_data
WHERE product_id = ? AND (cart_id IS NULL OR cart_id = ?)
LIMIT 1
`

type GetDigitalDataParams struct {
	ProductID string         `json:"product_id"`
	CartID    sql.NullString `json:"cart_id"`
}

// Digital Data queries
func (q *Queries) GetDigitalData(ctx context.Context, arg GetDigitalDataParams) (DigitalDatum, error) {
	row := q.db.QueryRowContext(ctx, getDigitalData, arg.ProductID, arg.CartID)
	var i DigitalDatum
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Content,
		&i.CartID,
	)
	return i, err
}

const getDigitalFiles = `-- name: GetDigitalFiles :many
SELECT id, product_id, name, ext, orig_name
FROM digital_file
WHERE product_id = ?
ORDER BY id
`

// Digital File queries
func (q *Queries) GetDigitalFiles(ctx context.Context, productID string) ([]DigitalFile, error) {
	rows, err := q.db.QueryContext(ctx, getDigitalFiles, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalFile{}
	for rows.Next() {
		var i DigitalFile
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Ext,
			&i.OrigName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, desc, slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE id = ? AND deleted = 0
LIMIT 1
`

// Product queries
func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, desc, slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE slug = ? AND deleted = 0
LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Desc,
		&i.Slug,
		&i.Amount,
		&i.Metadata,
		&i.Attribute,
		&i.Digital,
		&i.Active,
		&i.Deleted,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, name, ext, orig_name
FROM product_image
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetProductImageByID(ctx context.Context, id string) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getProductImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Ext,
		&i.OrigName,
	)
	return i, err
}

const getProductImages = `-- name: GetProductImages :many
SELECT id, product_id, name, ext, orig_name
FROM product_image
WHERE product_id = ?
ORDER BY id
`

// Product Image queries
func (q *Queries) GetProductImages(ctx context.Context, productID string) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, getProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Ext,
			&i.OrigName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, name, desc, slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE active = 1 AND deleted = 0
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListActiveProductsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT id, name, desc, slug, amount, metadata, attribute, digital, active, deleted, created, updated
FROM product
WHERE deleted = 0
ORDER BY created DESC
LIMIT ? OFFSET ?
`

type ListAllProductsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAllProducts(ctx context.Context, arg ListAllProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listAllProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Desc,
			&i.Slug,
			&i.Amount,
			&i.Metadata,
			&i.Attribute,
			&i.Digital,
			&i.Active,
			&i.Deleted,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE product
SET deleted = 1,
    updated = datetime('now')
WHERE id = ?
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteProduct, id)
	return err
}

const updateDigitalDataCart = `-- name: UpdateDigitalDataCart :exec
UPDATE digital_data
SET cart_id = ?
WHERE id = ?
`

type UpdateDigitalDataCartParams struct {
	CartID sql.NullString `json:"cart_id"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateDigitalDataCart(ctx context.Context, arg UpdateDigitalDataCartParams) error {
	_, err := q.db.ExecContext(ctx, updateDigitalDataCart, arg.CartID, arg.ID)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE product
SET name = ?,
    desc = ?,
    amount = ?,
    metadata = ?,
    attribute = ?,
    active = ?,
    updated = datetime('now')
WHERE id = ?
`

type UpdateProductParams struct {
	Name      string          `json:"name"`
	Desc      string          `json:"desc"`
	Amount    float64         `json:"amount"`
	Metadata  json.RawMessage `json:"metadata"`
	Attribute json.RawMessage `json:"attribute"`
	Active    bool            `json:"active"`
	ID        string          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Desc,
		arg.Amount,
		arg.Metadata,
		arg.Attribute,
		arg.Active,
		arg.ID,
	)
	return err
}
