// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM session
WHERE expires < ?
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context, expires sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredSessions, expires)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session
WHERE key = ?
`

func (q *Queries) DeleteSession(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, key)
	return err
}

const getSession = `-- name: GetSession :one
SELECT key, value, expires
FROM session
WHERE key = ?
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, key string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, key)
	var i Session
	err := row.Scan(&i.Key, &i.Value, &i.Expires)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT key, value, expires
FROM session
WHERE expires >= ?
ORDER BY expires DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, expires sql.NullInt64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessions, expires)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(&i.Key, &i.Value, &i.Expires); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSession = `-- name: SetSession :exec
INSERT INTO session (key, value, expires)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
  value = excluded.value,
  expires = excluded.expires
`

type SetSessionParams struct {
	Key     string         `json:"key"`
	Value   sql.NullString `json:"value"`
	Expires sql.NullInt64  `json:"expires"`
}

func (q *Queries) SetSession(ctx context.Context, arg SetSessionParams) error {
	_, err := q.db.ExecContext(ctx, setSession, arg.Key, arg.Value, arg.Expires)
	return err
}
