// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setting.sql

package sqlc

import (
	"context"
	"database/sql"
)

const bulkUpdateSettings = `-- name: BulkUpdateSettings :exec
UPDATE setting
SET value = CASE key
  WHEN ? THEN ?
  WHEN ? THEN ?
  WHEN ? THEN ?
  ELSE value
END
WHERE key IN (?, ?, ?)
`

type BulkUpdateSettingsParams struct {
	Value   sql.NullString `json:"value"`
	Value_2 sql.NullString `json:"value_2"`
	Value_3 sql.NullString `json:"value_3"`
	Value_4 sql.NullString `json:"value_4"`
	Value_5 sql.NullString `json:"value_5"`
	Value_6 sql.NullString `json:"value_6"`
	Key     string         `json:"key"`
	Key_2   string         `json:"key_2"`
	Key_3   string         `json:"key_3"`
}

func (q *Queries) BulkUpdateSettings(ctx context.Context, arg BulkUpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, bulkUpdateSettings,
		arg.Value,
		arg.Value_2,
		arg.Value_3,
		arg.Value_4,
		arg.Value_5,
		arg.Value_6,
		arg.Key,
		arg.Key_2,
		arg.Key_3,
	)
	return err
}

const createSetting = `-- name: CreateSetting :exec
INSERT INTO setting (id, key, value)
VALUES (?, ?, ?)
`

type CreateSettingParams struct {
	ID    string         `json:"id"`
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) error {
	_, err := q.db.ExecContext(ctx, createSetting, arg.ID, arg.Key, arg.Value)
	return err
}

const deleteSettingByKey = `-- name: DeleteSettingByKey :exec
DELETE FROM setting
WHERE key = ?
`

func (q *Queries) DeleteSettingByKey(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSettingByKey, key)
	return err
}

const getSettingByID = `-- name: GetSettingByID :one
SELECT id, key, value
FROM setting
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSettingByID(ctx context.Context, id string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByID, id)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT id, key, value
FROM setting
WHERE key = ?
LIMIT 1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingByKey, key)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}

const listAllSettings = `-- name: ListAllSettings :many
SELECT id, key, value
FROM setting
ORDER BY key
`

func (q *Queries) ListAllSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listAllSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.ID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettingByID = `-- name: UpdateSettingByID :exec
UPDATE setting
SET value = ?
WHERE id = ?
`

type UpdateSettingByIDParams struct {
	Value sql.NullString `json:"value"`
	ID    string         `json:"id"`
}

func (q *Queries) UpdateSettingByID(ctx context.Context, arg UpdateSettingByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateSettingByID, arg.Value, arg.ID)
	return err
}

const updateSettingByKey = `-- name: UpdateSettingByKey :exec
UPDATE setting
SET value = ?
WHERE key = ?
`

type UpdateSettingByKeyParams struct {
	Value sql.NullString `json:"value"`
	Key   string         `json:"key"`
}

func (q *Queries) UpdateSettingByKey(ctx context.Context, arg UpdateSettingByKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateSettingByKey, arg.Value, arg.Key)
	return err
}
