// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlite

import (
	"context"
)

const getPasswordByEmail = `-- name: GetPasswordByEmail :one
SELECT id, key, value
FROM setting
WHERE key = 'password'
LIMIT 1
`

func (q *Queries) GetPasswordByEmail(ctx context.Context) (Setting, error) {
	row := q.queryRow(ctx, q.getPasswordByEmailStmt, getPasswordByEmail)
	var i Setting
	err := row.Scan(&i.ID, &i.Key, &i.Value)
	return i, err
}
