// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_images.sql

package sqlite

import (
	"context"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_image (id, product_id, name, ext, orig_name)
VALUES (?, ?, ?, ?, ?)
RETURNING id, product_id, name, ext, orig_name
`

type CreateProductImageParams struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

type CreateProductImageRow struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (CreateProductImageRow, error) {
	row := q.queryRow(ctx, q.createProductImageStmt, createProductImage,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Ext,
		arg.OrigName,
	)
	var i CreateProductImageRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Ext,
		&i.OrigName,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_image WHERE id = ?
`

func (q *Queries) DeleteProductImage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProductImageStmt, deleteProductImage, id)
	return err
}

const deleteProductImages = `-- name: DeleteProductImages :exec
DELETE FROM product_image WHERE product_id = ?
`

func (q *Queries) DeleteProductImages(ctx context.Context, productID string) error {
	_, err := q.exec(ctx, q.deleteProductImagesStmt, deleteProductImages, productID)
	return err
}

const getProductImage = `-- name: GetProductImage :one
SELECT id, product_id, name, ext, orig_name
FROM product_image WHERE id = ? LIMIT 1
`

type GetProductImageRow struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

func (q *Queries) GetProductImage(ctx context.Context, id string) (GetProductImageRow, error) {
	row := q.queryRow(ctx, q.getProductImageStmt, getProductImage, id)
	var i GetProductImageRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Ext,
		&i.OrigName,
	)
	return i, err
}

const listAllProductImages = `-- name: ListAllProductImages :many
SELECT id, product_id, name, ext, orig_name
FROM product_image ORDER BY id
`

type ListAllProductImagesRow struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

func (q *Queries) ListAllProductImages(ctx context.Context) ([]ListAllProductImagesRow, error) {
	rows, err := q.query(ctx, q.listAllProductImagesStmt, listAllProductImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProductImagesRow{}
	for rows.Next() {
		var i ListAllProductImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Ext,
			&i.OrigName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, name, ext, orig_name
FROM product_image WHERE product_id = ?
ORDER BY id
`

type ListProductImagesRow struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	OrigName  string `json:"orig_name"`
}

func (q *Queries) ListProductImages(ctx context.Context, productID string) ([]ListProductImagesRow, error) {
	rows, err := q.query(ctx, q.listProductImagesStmt, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductImagesRow{}
	for rows.Next() {
		var i ListProductImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Ext,
			&i.OrigName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
